parent_data_dir: "rollout_nicfi_bing_zoom16"

data_dirs:
  predict_imgs_root: "model_tiles"
  predict_masks_root: "predict_masks"

data_transform_settings:
  rescale_image_method: "normalize_clip_and_rescale"
  data_augmentation_transforms: []

random_seed: 1001

dataloader_settings:
  batch_size: 128
  num_workers: 4

# the model settings are necessary to normalize the images appropriately
model_settings:
  encoder_name: "resnet50"
  encoder_weights: "imagenet"
